### PR TITLE
v0.3.0 release

### PR DESCRIPTION
**Pull request by acolytec3**
Update changelog and prepped for new release

### CODE REVIEW

**Review by gabrocheleau — APPROVED** [review]

**Comment by holgerd77** [comment]
@acolytec3 Ok, seems there is no actual release on this out yet (I have sent you the invite, haven't I)?

Will do this now.

**Comment by holgerd77** [comment]
(so: do the release)

**Comment by acolytec3** [comment]
Yep, was govt to get to it this morning but happy for you to do it too

**Comment by holgerd77** [comment]
Have published this as [v0.3.0](https://github.com/ethereumjs/verkle-cryptography-wasm/releases/tag/verkle-cryptography-wasm%400.3.0) on npm.

**Pull request merged**
