### PR TITLE
New Release v0.1.1

### PR DESCRIPTION
**Pull request by holgerd77**
Some improvements and additional exposures we likely need on implementation

### CODE REVIEW

**Comment by holgerd77** [comment]
Have already published as `v0.1.1` due to some time constraints, still to be merged though.

**Comment by holgerd77** [comment]
@gabrocheleau so `getTreeKeyHash()` is basically the `pedersonHash()` method

**Review by acolytec3 — APPROVED** [review]
LGTM!

**Review by acolytec3 — CHANGES_REQUESTED** [review]
Actually, just kidding, `npm run build` doesn't appear to work locally right now.  Will research

**Review by acolytec3 — APPROVED** [review]
Have fixed one minor directory issue in `rust-build.sh` and will now approve.

**Pull request merged**
