### PR TITLE
chore: update to arkworks 0.4

### PR DESCRIPTION
**Pull request by kevaundray**
Updates to arkworks version 0.4.

EDIT: This does not make any API changes

### CODE REVIEW

**Comment by kevaundray** [comment]
The tests that are failing don't seem to be useful -- wam-pack test was for test marked with `#[wasm_bindgen_test]` -- we had this in the old API, but right now all tests are being ran in typescript.

If we want to run rust tests, then just calling `cargo test` would be the best option here.

Looking on master, the CI run confirms this with the `no tests to run!` comment at the bottom

**Comment by kevaundray** [comment]
Changed the CI to run js tests in #7

**Review by holgerd77 — APPROVED** [review]
Have resolved the merge conflicts by the test-update API and dependency changes, tests are passing now and will merge, looks good!

Could you give a brief description of the changes on the API level?

**Comment by kevaundray** [comment]
> Have resolved the merge conflicts by the test-update API and dependency changes, tests are passing now and will merge, looks good!
> 
> Could you give a brief description of the changes on the API level?

Yep! This should not make any API changes for javascript consumers, so its non-breaking

**Pull request merged**
