### PR TITLE
Add `*Proof` functions to `verkleFFI`

### PR DESCRIPTION
**Pull request by acolytec3**
Exposes the `createProof` and `verifyProof` functions to Javascript

### CODE REVIEW

**Review by acolytec3 — COMMENTED** [review]
This isn't ready to merge yet as I want to clean up the outer typescript bindings so it's not just a pass through but this is my first attempt at exposing the proof functions to Javascript.  Will test locally and see if I'm about to create and verify proofs or not.

**Review by acolytec3 — COMMENTED** [review]
To test this locally:

Checkout this branch.

```sh
npm run build // from the repo root
npm link
```

Next, clone the `ethereumjs-monorepo` and check out this commit - 446cd45c78b5c8fbf18bf12a3304693eddb3766a
```sh
git clone https://github.com/ethereumjs/ethereumjs-monorepo.git
cd ethereumjs-monorepo
git checkout 446cd45c78b5c8fbf18bf12a3304693eddb3766a
npm i
cd packages/verkle
npm link verkle-cryptography-wasm
npx vitest run test/proof.spec.ts
```

**Review by gabrocheleau — APPROVED** [review]
Looks good to me.

I've taken a look at the tests from the ethjs-monorepo side, and I can't spot what's wrong with it, will need to wait for kev to chime in. However the verkle-crypto-wasm side is quite lean and straightforward, so I'm approving it here.

**Review by kevaundray — APPROVED** [review]

**Comment by kevaundray** [comment]
Approved as the API looks correct to me

**Comment by acolytec3** [comment]
I suspect something is wrong somewhere (though maybe on the ethjs side and not here).  Will merge for now so the functions are exposed and will do a followup PR to make the JS API easier to use (i.e. let you pass in the various fields and then the wrapper function will serialize according to what Rust wants).

**Pull request merged**
