### PR TITLE
chore!: modify `getTreeKeyHash` to use `hashCommitment`

### PR DESCRIPTION
**Pull request by kevaundray**
Supercedes #24 

Once the go-ethereum PR has been merged, we can merge this

### CODE REVIEW

**Comment by holgerd77** [comment]
Updated this PR to take the merged WASM path fix into account (needed a conflict resolution).

**Comment by kevaundray** [comment]
https://github.com/gballet/go-ethereum/pull/401#event-12246413418 has been merged which unblocks this PR

**Review by acolytec3 — APPROVED** [review]
LGTM

**Comment by acolytec3** [comment]
@kevaundray I'm assuming we need to do an updated release on this one, right?

**Comment by kevaundray** [comment]
> @kevaundray I'm assuming we need to do an updated release on this one, right?

Yep! This is a breaking change for downstream

**Comment by acolytec3** [comment]
And just to confirm my understanding, this also changes how the stems are computed so we should expect different outputs from `getTreeKey`, right?  Just want to make sure since I need to update the tests for the downstream code in `@ethereumjs/verkle`

**Comment by kevaundray** [comment]
> And just to confirm my understanding, this also changes how the stems are computed so we should expect different outputs from `getTreeKey`, right? Just want to make sure since I need to update the tests for the downstream code in `@ethereumjs/verkle`

Yep, exactly -- this changes getTreeKeyHash which is used by getTreeKey

**Pull request merged**
